//------------------------------------------------------------------------------
// <auto-generated>
//     This code is generated by a tool。
//     Run-time version: 4.0.30319.1026
//
//     Changes to this document may lead to incorrect behaviour，And if
//     Recreate Code，These changes will be lost.。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WGController32_CSharp.Properties
{


    /// <summary>
    ///   A powerful type of resource class，Strings used to find localized, etc.。
    /// </summary>
    // This kind of thing is... StronglyTypedResourceBuilder
    // Class adoptions similar to ResGen or Visual Studio The tool is automatically generated.。
    // To Add or Remove Members，Please edit .ResX Documentation，And rerun. ResGen
    // (Here. /str As Command Options)，or regenerated VS Item。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns such use、Cache ResourceManager Examples。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WGController32_CSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Finds rewrites for all resources CurrentUICulture Properties，
        ///   By using this powerful type of resource Category。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
